apiVersion: v1
kind: Service
metadata:
  labels:
    app: vectordb-weaviate
  name: vectordb-weaviate
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: vectordb-weaviate
  type: ClusterIP