apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura-v3
  name: hasura-v3
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hasura-v3
  type: ClusterIP