apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura-authorization-advanced
  name: hasura-authorization-advanced
  namespace: learn 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hasura-authorization-advanced
  type: ClusterIP