apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura-v3-supergraph
  name: hasura-v3-supergraph
  namespace: learn
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hasura-v3-supergraph
  type: ClusterIP
